name: can-i-run-it
services:

  # FastAPI
  backend:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.backend
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    container_name: ciri-backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-4000}:${BACKEND_PORT:-4000}"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ../backend:/app/backend
    networks:
      - ciri-net

  react:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile_dev
    container_name: ciri-react
    depends_on:
      - backend
      - mongodb
    env_file:
      - .env
    ports:
      - "${REACT_PORT:-3000}:${REACT_PORT:-3000}"
    networks:
      - ciri-net
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_BASE_URL=http://localhost:${BACKEND_PORT:-4000}/api

    volumes:
      - ../frontend:/app
      - /app/node_modules

  mongodb:
    image: mongo:7.0.15
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping')\""]
      start_period: 15s
      interval: 30s
      timeout: 10s
      retries: 3
    container_name: ciri-mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - ciri-net
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    restart: unless-stopped

volumes:
  mongo_data:
  mongo_config:

networks:
  ciri-net:
