name: can-i-run-it-prod
services:

  # NestJS backend (Production)
  backend:
    container_name: ciri-backend-prod
    build:
      context: ../backend
      dockerfile: ../infra/Dockerfile.backend
      target: prod
    environment:
        - ENV=production
        # Internal Docker networking uses service names, so this is fine
        - REACT_URL=http://ciri-frontend-prod
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ciri-net-prod

  # React Frontend (Production - Nginx)
  react:
    container_name: ciri-frontend-prod
    build:
      context: ../frontend
      dockerfile: ../infra/Dockerfile.frontend
      target: prod
    env_file:
      - .env
    ports:
      - "${REACT_PORT}:80" # Nginx listens on 80 inside the container
    networks:
      - ciri-net-prod
    environment:
      # This variable must be baked in at build time for React, 
      # but we leave it here for clarity or runtime config injection if you add it later.
      - REACT_APP_BASE_URL=http://localhost:${BACKEND_PORT}/api

  # Postgres (Same as dev, but separate container/volume name to avoid conflicts)
  postgres:
    image: postgres:16-alpine
    container_name: ciri-postgres-prod
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
    networks:
      - ciri-net-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata-prod:

networks:
  ciri-net-prod: